url: https://diegomagela.github.io
domain: diegomagela.github.io
url: https://my-site.github.io 



title: Diego Magela
description: My personal website

name: Diego Magela
bio: PhD candidate at University of São Paulo.
     Interested in nonlinear aeroelasticity, 
     nonlinear finite element method, 
     unsteady aerodynamics,
     and computational fluid dynamics.
     Mathematics,
     Linux,
     LaTeX,
     and Chess enthusiast.
     
avatar: assets/avatar/avatar.jpg
favicon: /assets/favicon/favicon.ico
 

twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge